### ISSUE TITLE
On Disk Build Failing v1.16.0

### ISSUE THREAD

**Issue by barrycarey** [spotify/annoy#404] opened 2019-08-11 19:31 UTC
The latest version fails to build the index on disk. 

Building the index results in 

`Error truncating file: Input/output error`

Same code works on 1.15.2. 

Python 3.7 Windows 10

**Comment by erikbern** [comment] 2019-08-12 03:35
Can you share code reproducing the error?

thanks

**Comment by barrycarey** [comment] 2019-08-12 12:20
`
index = AnnoyIndex(64)
index.on_disk_build('test.ann')
with conn.cursor() as cur:
    cur.execute("SELECT id, hash FROM some_table")
    for row in cur:
        vector = list(bytearray(row['hash'], encoding='utf-8'))
        index.add_item(row['id'], vector)
index.build(20)
`

**Comment by barrycarey** [comment] 2019-08-12 12:22
```
    index = AnnoyIndex(64)
    index.on_disk_build('test.ann')
    with conn.cursor() as cur:
    cur.execute("SELECT id, hash FROM some_table")

    for row in cur:
        vector = list(bytearray(row['hash'], encoding='utf-8'))
        index.add_item(row['id'], vector)
    index.build(20)
```

**Comment by erikbern** [comment] 2019-08-12 17:29
ok, will add a unit test and see what i can do about it

**Comment by cquliujian** [comment] 2020-06-11 08:33
I have same problem，

**Comment by erikbern** [comment] 2020-06-11 18:29
do you have a code sample that reproduces the issue consistently?

**Comment by vbod** [comment] 2020-06-25 11:45
@erikbern Please read the issue I opened (https://github.com/spotify/annoy/issues/487). Both `save()` and `on_disk_build()` might fail for large datasets (@barrycarey what's the size of your dataset btw?) because `long` on Windows platform is a 32-bit structure (I know, weird but legacy ^^), so you'd need to pass by a 64-bit structure and use the Windows API for large files (namely `SetFilePointerEx` instead of `SetFilePointer`). I posted a stub for fixing `save()` only. 

There's another issue with `on_disk_build()` as you can't truncate a memory-mapped on Windows (ERROR_USER_MAPPED_FILE, 1224) and that would actually need a bit more work (though quite simple as well).

**Comment by barrycarey** [comment] 2020-06-25 18:34
@vbod ~120 million items

**Comment by erikbern** [comment] 2020-06-27 13:02
thanks. any pointers on how to fix? if you want to submit a pull request, that would be amazing!

**Comment by vbod** [comment] 2020-07-06 13:42
@erikbern A bit overwhelmed by now, but sure I'll do my best to create a proper PR for handling that Windows case - at least `save()` which is quite easy, `build_on_disk()` requires more work.

**Comment by erikbern** [comment] 2020-07-06 14:00
ok, no rush! really appreciate it

**Comment by AlxndrMlk** [comment] 2020-07-22 12:46
Hi everyone!

I face a similar issue with only 1000 elements:

```# Define embedding vector dimesion
EMB_DIM = 300
N_VECS = int(1e3)
N_TREES = 30
idx_filename = '__ANNOY_1e3_large_idx.ann'

# Initialize the index
idx_large = AnnoyIndex(EMB_DIM, 'angular')

# Disk-build
idx_large.on_disk_build(idx_filename)

for i in tqdm(range(N_VECS)):
    vec = np.random.randn(EMB_DIM)
    idx_large.add_item(i, vec)

idx_large.build(N_TREES) # n trees


---------------------------------------------------------------------------

100%|████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:00<00:00, 5939.36it/s]

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-7-4f0ed0fbfa02> in <module>
      3     idx_large.add_item(i, vec)
      4 
----> 5 idx_large.build(N_TREES) # n trees

Exception: Unable to truncate: Input/output error (5)
```

@vbod - if I can help somehow, feel free to let me know.

Best,
Aleksander

**Comment by erikbern** [comment] 2020-07-22 15:49
odd. will see if i can repro.

**Comment by vbod** [comment] 2020-07-23 10:01
@AlxndrMlk Are you using Windows? 

In that case I guess this is the bug I opened in #487 (or at least related). In your case you're not having errors with `ftruncate` on too large file I guess but as far as I can tell, no matter how big the file is, `on_disk_build()` should fail on Windows.

It is due to the fact that a file is created, then mmaped, and when build is called then last chunks are truncated. But truncation cannot happen on Windows when a file is already mmap-ed, cf. [here](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/18d8fbe8-a967-4f1c-ae50-99ca8e491d2d) -  honnestly I thought it was OK when in the same process but I found it wasn't when debugging... In order to fix I guess one has to follow [Microsoft's guidelines](https://docs.microsoft.com/fr-fr/windows/win32/api/fileapi/nf-fileapi-setendoffile?redirectedfrom=MSDN): 
> If CreateFileMapping is called to create a file mapping object for hFile, UnmapViewOfFile must be called first to unmap all views and call CloseHandle to close the file mapping object before you can call SetEndOfFile.

I'll try to push a PR to deal with it when I come back from my vacations 👓

**Comment by AlxndrMlk** [comment] 2020-07-23 14:14
Yes @vbod, exactly, Win 10. 

Seems that's the issue. 

Have a great holiday, by the way! 😎

**Comment by vbod** [comment] 2020-07-27 13:01
@AlxndrMlk @barrycarey If you ever have the opportunity to test with the master branch, it'd be awesome to know if [this PR](https://github.com/spotify/annoy/pull/494) does fix it indeed! Please tell me if it does - or not 😉

**Comment by erikbern** [comment] 2020-07-27 13:12
Closing this for now! Will reopen if bug persists

**Closed by erikbern** 2020-07-27 13:12 UTC

**Comment by AlxndrMlk** [comment] 2020-07-27 17:17
@vbod, thanks! I'll check as soon as I find a while to do so.

Best,
Aleksander
