### ISSUE TITLE
Broken index with many zero (empty) vectors.

### ISSUE THREAD

**Issue by isamaru** [spotify/annoy#249] opened 2017-11-28 12:34 UTC
We created an annoy index with millions of vectors, many of which were actually zero vectors (vectors of [0.0, 0.0, ...]).
The resulting index returned results which were very far away from the searched vector.
I debugged annoy and found out that many nodes in the search tree had vectors full of "nan" values. Presence of these nodes broke the search algorithm.

Version: reproducible with 1.8.0 and 1.10.0.
Environment: Python 3.6.3, Ubuntu 17.10 (64-bit)

**STR:** build index (angular distance) from 100000 random vectors + 100 zero vectors (shuffle order). Search for any non-zero vector using get_nns_by_item(i, 10)
**AR:**
  Index is built without errors.
  When searching for most vectors (such as with get_nns_by_item), the searched vector is not among the results, and they are very far off.
  I debugged the search and many tree nodes were built with vectors of nan value (including some root nodes). Search hits these nodes and the results are garbage.
**ER:**
 either:
    -- raise an exception when building the index and nodes are corrupted
  or:
    -- searching for non-zero vectors works normally
    -- when searching for a vector present in the index, it is always retrieved (the algorithm is supposed to work that way AFAIK)
 
suggestion: perhaps annoy could detect zero vectors when they are added, do not index them and instead store their ids in a separate structure

**Comment by erikbern** [comment] 2017-11-28 13:10
This makes sense. I consider this arguably a "user error" since the distance to the zero vector is undefined (or nan) but I agree the error could be more useful to humans.

Annoy support "holes" now (see #223) so we could probably make something similar. Maybe if the vector has length <= eps, then just don't insert it.

I'd appreciate a pull request (including a unit test). Let me know if you want to put that together an if you need any pointers.

**Comment by a1k0n** [comment] 2017-11-28 15:42
I'm guessing the underlying cause of this, however, is finding the split vector based on a random pair, and if both are zero vectors, the split is the NaN vector. So maybe the splitter could also check that the distance between random vectors is > eps?

**Comment by a1k0n** [comment] 2017-11-28 15:44
This might also explain the observations in #223 -- that newer annoy is less robust to zero vectors, because instead of random splits, it splits based on random input vector pairs, and that could be an invalid split in the presence of "bad" inputs.

**Comment by erikbern** [comment] 2017-11-28 20:17
@a1k0n if that's correct then another broken case would be if you create an index with a lot of (nonzero) vectors that are identical. That should be easy to reproduce. I'll put together a unit test for this to make sure it doesn't degrade

**Comment by erikbern** [comment] 2018-03-31 19:14
This should be resolved by https://github.com/spotify/annoy/pull/276

**Closed by erikbern** 2018-03-31 19:14 UTC
