### ISSUE TITLE
Item index larger than the largest item index

### ISSUE THREAD

**Issue by yogesh-kamble** [spotify/annoy#261] opened 2018-01-05 09:04 UTC
I am getting following error
```Item index larger than the largest item index```
I am getting this error for index 4166.
but I am storing this index while building index.ann file.
Is there any limit for indexes to store ?

**Comment by yogesh-kamble** [comment] 2018-01-05 14:11
while iterating in for loop to add_item if we skip some of the index and then build tree then tree will also skip those index and build tree using sequential index.
```
for file_index, i in enumerate(infiles):  # length of infiles is 27
    if file_index not in (1, 2):
        print(str(file_index) + ' ' + i)
        file_vector = np.loadtxt(i)
        print("Adding index %s" % file_index)
        t.add_item(file_index, file_vector)
t.build(trees)
```
in above case I am iterating through list of 27 items and skipping the 1, 2 index. and now If I search for 26 index it gives
```Item index larger than the largest item index```
but add_item add 26 index and it's just skipping 1,2 index.

**Comment by erikbern** [comment] 2018-01-05 14:18
Weird. Can you give me a small reproducible example?

**Comment by nixphix** [comment] 2018-01-13 06:01
Problem is not with skipped vectors but the vector id is mixed up with the vector index while saving and loading the tree.

Following will recreate the issue:

```
from annoy import AnnoyIndex
import random
import numpy as np
f = 40
t = AnnoyIndex(f)
vec_ids = list()
for i in range(1000):
    vec_ids.append(i * 1000)    
    v = np.array([random.gauss(0, 1) for z in range(f)])
    t.add_item(vec_ids[-1], v)
t.build(10) # 10 trees
t.save('test.ann')
u = AnnoyIndex(f)
u.load('test.ann')
print(u.get_nns_by_item(random.choice(vec_ids), 1000)) 
```

**Comment by cggaurav** [comment] 2018-01-24 14:58
Hey @yogesh-kamble is there a reproducible example from you? We have a similar problem that we are debugging.

**Comment by erikbern** [comment] 2018-01-28 02:01
I just saw something similar locally actually. This is for a large index (1e6 elms, 200 dimensions). Trying to repro.

**Comment by erikbern** [comment] 2018-01-28 02:25
I figured out what happened in my case. Turns out my disk ran out of memory while saving the index. We don't check whether `fwrite` succeeds. Should probably enable that. Could even write to a temp file and move it after closing it just to make sure.

@cggaurav @yogesh-kamble is it possible you had some similar problem?

**Comment by erikbern** [comment] 2018-01-28 02:26
I'm also going to add some checks to make sure that loading a garbage index fails

**Comment by erikbern** [comment] 2018-01-28 02:27
It's also possible you're trying to load an index created using euclidean distance using a different distance maybe?

**Comment by yogesh-kamble** [comment] 2018-02-02 16:54
Yes we are loading index using euclidean distance.

**Comment by erikbern** [comment] 2018-02-02 18:14
ok i would say generally when this problem happens, it's because annoy fails to parse the index properly. could be either

* the index was corrupted during saving (out of disk space)
* you're loading it with a different distance function than it was saved with
* you're loading it with a different number of dimensions than it was saved with

**Comment by cggaurav** [comment] 2018-02-02 20:11
@erikbern We use just euclidean and this seems to be the index being corrupted during saving and will be adding exception handling for our `.save()` calls for further info.

**Comment by erikbern** [comment] 2018-02-02 22:00
If you want to patch `save` in the C++ layer so that it catches any exceptions during saving, that would be nice

**Comment by erikbern** [comment] 2018-02-14 14:00
Wonder if it's the same as #279

**Closed** 2018-03-31 19:30 UTC
