### ISSUE TITLE
Incorrect AnnIndex load/search nn triggers Segmentation Fault

### ISSUE THREAD

**Issue by midneet** [spotify/annoy#394] opened 2019-06-24 04:46 UTC
Hi,
I'm not sure if this has been issued or not. I found the error message is kind of misleading when I load incorrect Ann index to do get_nns_by_vectors
here is what I was doing:

t = AnnIndex(4096, metric='angular')
t.load('A.ann') <-- This ann index is actually of dimension=768 when I build this index, but no error occurs
test = np.ones(4096)
t.get_nns_by_vector(test, n=3) <-- this trigger Segmentation fault with no other error message
_____________________
However, when I tried more times with this code, it sometimes returns results of "two" nns, which is also not the number of nns I want.

I figure out my problem myself when I notice I just load the wrong index, but I think the error message of Segmentation Fault didn't reveal the actual wrong place of codes. I'm wondering if you would mind correcting such error check? thank you

**Comment by erikbern** [comment] 2019-07-02 23:20
Thinking about it some more it might actually make sense to have two separate Python classes so we reduce the risks of this mistake

**Comment by erikbern** [comment] 2019-07-05 15:55
Actually realized the problem isn't the metric, it's the number of dimensions... I'll see if I can add an exception to this as well

**Comment by erikbern** [comment] 2019-07-07 12:11
Sort of fixed in #397

**Closed by erikbern** 2019-07-07 12:11 UTC
