### ISSUE TITLE
Is there a possibility to add label/data to the items

### ISSUE THREAD

**Issue by n1ru4l** [spotify/annoy#454] opened 2020-02-13 13:21 UTC
For my use-case, I want to apply some post-filtering to the query result based on the input. Right now I would have to load the data from an external source such as Redis by using the returned indexes from the `get_nns_by_vector ` or `get_nns_by_item ` method.

Would it be possible to specify some data that is stored along with the item which is added via the `add_item` method (e.g. as a third parameter)? It could then be returned as part of the result returned from `get_nns_by_vector` and `get_nns_by_item`, or at least be accessible via some other method that looks up the label/associated data via the index?

With that functionality, it would be possible to not require loading additional data source for retrieving the actual id of a result (or any other associated data).

**Comment by piskvorky** [comment] 2020-02-13 13:34
Dupe of https://github.com/spotify/annoy/issues/48

**Comment by n1ru4l** [comment] 2020-02-13 13:57
Thank you :D

**Closed** 2020-02-13 13:57 UTC
